version: '3'
volumes: 
  db-data: {}
services:
  api:
    build: bjs-api/api
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=bjs-org
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./bjs-web/web:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./keys/localhost.key:/etc/ssl/private/localhost.key
      - ./keys/localhost.crt:/etc/ssl/certs/localhost.crt
    depends_on:
      - api